apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  selector:
    app: customer
  ports:
#   if we use port 80, http calls could look like that: http://<service_name> (without explicit port, e.g, :8080)
    - port: 80
      targetPort: 8080
  type: LoadBalancer
